### ISSUE TITLE
Changing the default style from Manage Style causes problems

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/unesco-ihp#354]
If you try to disable the default style from the Manage Style tool, the style remains present in the layer preview and causes an error in the legend.
See [this layer](http://ihp-wins.unesco.org/layers/geonode:a__1503_Elevaciones_3gaZjr6)
**How to Reproduce**
follow the steps in the gif:
![DEFAULT_STYLE](https://user-images.githubusercontent.com/56537133/118157962-7aa9d800-b41b-11eb-8fe7-03e76002dce0.gif)

**Comment by simboss** [comment]
@ElenaGallo can you test this one again on unesco?
It should have been fixed.

**Comment by ElenaGallo** [comment]
@simboss @giohappy Changing the default style the error persists.

**How to Reproduce**
follow the steps in the gif:
![legend](https://user-images.githubusercontent.com/56537133/119485066-f0387100-bd56-11eb-94e5-285c63f436a4.gif)

**Comment by giohappy** [comment]
@marthamareal was this issue supposed to be solved with the fixes you did to styles and legends?
Apprently it's still there, please have a look.

**Comment by marthamareal** [comment]
Apparently, the edge-case where the style names have a similarity eg `a__1503_Elevaciones` and `a__1503_Elevaciones_3gaZjr6` was not caught, and hence this condition will pass since it does not match the name https://github.com/geosolutions-it/unesco-ihp/blob/master/ihp/templates/layers/layer_detail.html#L620

**Comment by marthamareal** [comment]
@giohappy  we can solve this by retrieving the exact name from the url eg `http://ihp-wins.unesco.org/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image/png&WIDTH=20&HEIGHT=20&LAYER=geonode:a__1503_Elevaciones_3gaZjr6&STYLE=a__1503_Elevaciones&legend_options=fontAntiAliasing:true;fontSize:12;forceLabels:on`

We get the value between `STYLE=` and `&` eg legend_url_style
Then we change this condition to `{% if legend.link_type == 'image' and style_name == legend_urlstyle%}

**Comment by giohappy** [comment]
Why did you close this @marthamareal?

Rather the doing manual splitting you can use [urlparse](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse).

**Comment by marthamareal** [comment]
> Why did you close this @marthamareal?

sorry this wasn't intentional
