### ISSUE TITLE
WP8 [B28] - Layers

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#50]
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Fix bug related to the upload of layers.
User A uploads a layer called XYZ in which information is represented in red, orange and yellow. Usesr A decides to delete the layer, and re-uploads the same layer named XYZ, but this time in dark blue, medium blue, light blue. The layer is displayed in red, orange and yellow. It is only if the name of the files uploaded are changed that the layer will be displayed with the correct colours. 
It seems that WINS keep in memory all layers updated and deleted, and reapply the parameters whenever the same files name is used a second time.

**Comment by afabiani** [comment]
Should be fixed. Please test it again and let me know if there's still something replaced during the upload.

**Comment by meyerch** [comment]
I just tested it and the problem is still there.
I uploaded a first layer "tba-test" that looked like this:
![test-replacement-style.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fc918937cf91ac9fe5be40a150f59a3d0b34673008a6693cc7f33ab0487e021b4d44be44510e10f8fc8d7df0e739728f0a0bedd26d5b74c73817aeaa9e0dfd50e474d412dcfce9c85ecafa3c2ded8a8a4f361701198dfe593da4915985.PNG)

Then I deleted it, and replace with a layer with the same name but a different style, that looked like this:
![test-replacement-style2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fc918937cf91ac9fe5be40a150f59a3d0b34673008a67932c9a138ad4d71040c1b5ca6535d5615a8fd8c2ff0e06d7588595dedd16e5f70c63c14aaba9003ad43eb7edf10d8eff6df0ed2e22f24ee818e4a3e160c1c88fb5b3da49f4bda15.PNG)

And on WINS, I ended up with the same style as for the first layer. Interestingly, when I click on "layer style ", the correct style appears in the window:
![test-replacement-style3.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fc918937cf91ac9fe5be40a150f59a3d0b34673008a67832c9a138ad4d71040c1b5ca6535d5615a8fd8c2ff0e06d7588595dedd16e5f70c63c14aaba9003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3e160c1c88f95d31a29149da15.PNG)

**Comment by afabiani** [comment]
I guess it is the usual browser cache problem. Will double check anyway.

**Comment by meyerch** [comment]
Nevermind, I just reclick on CTRL+F5 one more time, and the layer is now correctly displayed...

So this is ACCEPTED

**Comment by meyerch** [comment]
![test-replacement-style4.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fc918937cf91ac9fe5be40a150f59a3d0b34673008a67f32c9a138ad4d71040c1b5ca6535d5615a8fd8c2ff0e06d7588595dedd16e5f70c63c14aaba9003ad43eb7edf10d8eff6df0ed2e22f27e6818e4a3e160c1c8bff5a3da59b4cda15.PNG)

**Comment by simboss** [comment]
Browsers today have aggressive caching which is difficult to circumvent with quick modifications of content.

In the longer run we shall enhance GeoNode mapviewers to explicitly add a token to invalidate explicitly content (i.e. images) in the browsers' cache when someone updates the data like you did.

**Comment by meyerch** [comment]
Thank you for the precisions. 

For now, I dont see it as an emergency, especially since we can put a disclaimer in our 'Get Started' guide, advising users to clean the cache regularly, particularly when editing layers. 
But let's keep this in mind for post-Phase 1.
